server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    testWhileIdle: true
    validationQuery: SELECT 1
  database:
    driverClassName: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: true
    circuitbreakers:
      enabled: true

eureka:
  instance:
    #physical ip instead of name
    preferIpAddress: true
  client:
    #register with eureka or not (config service don`t register with eureka)
    registerWithEureka: true
    #????? ?? ?????? ??????? ????????? ????? ??????? (true - ???????? ?? ?????????)
    #??? ??????? ????? ??????? ?????? ????? ????????? ?? ???? ?????? ????? ??? ?? ??????
    #?????? 30 ? ?????? ????? ??????????? ? Eureka ? ????????? ????? ???????
    fetchRegistry: true
    serviceUrl:
      #?????????????? ?????? Eureka
      defaultZone: http://localhost:8070/eureka/

resilience4j.circuitbreaker:
  instances:
    licenseService:
      #Export resilience4j info in actuator-health endpoint
      registerHealthIndicator: true
      #Size buffer for unsuccessful calls
      ringBufferSizeInClosedState: 5
      #Size buffer for unsuccessful calls in half-open state
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 10s
      #percentage failure rate threshold
      failureRateThreshold: 50
    organizationService:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 6
      ringBufferSizeInHalfOpenState: 4
      waitDurationInOpenState: 20s
      failureRateThreshold: 60

resilience4j.bulkhead:
  instances:
    bulkheadLicenseService:
      maxWaitDuration: 10ms
      maxConcurrentCalls: 2

resilience4j.thread-pool-bulkhead:
  instances:
    bulkheadLicenseService:
      maxThreadPoolSize: 1
      coreThreadPoolSize: 1
      queueCapacity: 1
      keepAliveDuration: 20ms

resilience4j.retry:
  instances:
    retryLicenseService:
      maxRetryAttempts: 5
      waitDuration: 10000
      retry-exceptions:
        - java.util.concurrent.TimeoutException

resilience4j.ratelimiter:
  instances:
    licenseService:
      timeoutDuration: 1000ms
      limitRefreshPeriod: 5000
      limitForPeriod: 5

logging:
  level:
    org.springframework.web: WARN
    com.optimagrowth: DEBUG