server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    testWhileIdle: true
    validationQuery: SELECT 1
  database:
    driverClassName: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/spmia-realm

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

logging:
  level:
    org.springframework.web: WARN
    com.optimagrowth: DEBUG
    org.springframework.security: DEBUG

keycloak:
  realm: spmia-realm
  auth-server-url: http://localhost:8080
  ssl-required: external
  resource: ostock
  credentials.secret: edOFCheutEAlEAPsXqCUSbqxyUtZeAet
  use-resource-role-mappings: true
  bearer-only: true